baseurl: /site # no custom domain
repository: FrancescoBollini/site # local testing (https://help.github.com/articles/repository-metadata-on-github-pages/)

exclude: [Gemfile, Gemfile.lock]

plugins:
  - jekyll-redirect-from

