repository: FumettiUSB/FumettiUSB.github.io # local testing (https://help.github.com/articles/repository-metadata-on-github-pages/)

exclude: [Gemfile, Gemfile.lock]

plugins:
  - jekyll-redirect-from

prose:
  rooturl: "_posts"
  media: "assets"
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "published"
        field:
          element: "checkbox"
          label: "published"
          value: "true"
