baseurl: /site # no custom domain
repository: FrancescoBollini/site # local testing (https://help.github.com/articles/repository-metadata-on-github-pages/)

exclude: [Gemfile, Gemfile.lock]

plugins:
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: ""
    values:
      project: "sito"
      version: "1.2.3"
      tagline: "Sito di Pito"
      release: "https://github.com/FrancescoBollini/site/releases/tag/v1.2.3"
