repository: FumettiUSB/FumettiUSB.github.io # local testing (https://help.github.com/articles/repository-metadata-on-github-pages/)

exclude: [Gemfile, Gemfile.lock]

plugins:
  - jekyll-redirect-from

sections:
  - text: Fumetti
    url: /comics/
  - text: Non-Fumetti
    url: /things/
  - text: Spiegazioni
    url: /about/

prose:
  rooturl: "_posts"
  media: "assets"
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "published"
        field:
          element: "checkbox"
          label: "published"
          value: "true"
      - name: "category"
        field:
          element: "select"
          label: "category"
          value: "comics"
          options:
            - name: 'Comics'
              value: 'comics'
            - name: 'Things'
              value: 'things'

